apiVersion: v1
kind: Service
metadata:
  name: zomato-service
spec:
  selector:
    app: zomato
  type: LoadBalancer  # Use NodePort if LoadBalancer isn’t supported
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
